#!/bin/bash
# // Exporting Language to UTF-8
export LC_ALL='en_US.UTF-8'
export LANG='en_US.UTF-8'
export LANGUAGE='en_US.UTF-8'
export LC_CTYPE='en_US.utf8'

# // Export Color & Information
export RED='\033[0;31m'
export GREEN='\033[0;32m'
export YELLOW='\033[0;33m'
export BLUE='\033[0;34m'
export PURPLE='\033[0;35m'
export CY='\033[0;36m'
export LIGHT='\033[0;37m'
export NC='\033[0m'

# // Export Banner Status Information
export EROR="[${RED} EROR ${NC}]"
export INFO="[${YELLOW} INFO ${NC}]"
export OKEY="[${GREEN} OKEY ${NC}]"
export PENDING="[${YELLOW} PENDING ${NC}]"
export SEND="[${YELLOW} SEND ${NC}]"
export RECEIVE="[${YELLOW} RECEIVE ${NC}]"

# // Export Align
export BOLD="\e[1m"
export WARNING="${RED}\e[5m"
export UNDERLINE="\e[4m"

# // Exporting URL Host
export Server_URL="autosc.me/aio"
export Server_Port="443"
export Server_IP="underfined"
export Script_Mode="Stable"
export Auther="XdrgVPN"

function garis() {
echo -e "${CY}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
}

url_izin="https://raw.githubusercontent.com/Bangjago2/permision/main/ultra"
ipsaya=$(curl -sS ipv4.icanhazip.com)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
checking_sc() {
useexp=$(wget -qO- $url_izin | grep $ipsaya | awk '{print $3}')
if [[ $date_list < $useexp ]]; then
echo -ne
else
lane
echo -e "\033[42m          ULTRAMENSTORE AUTOSCRIPT          ${exitsc}"
lane
echo -e ""
echo -e "            \033[0;35mPERMISSION DENIED !${exitsc}"
echo -e "   ${j}Your VPS${exitsc} $ipsaya ${j}Has been Banned${exitsc}"
echo -e "     ${j}Buy access permissions for scripts${exitsc}"
echo -e "             ${j}Contact Admin :${exitsc}"
echo -e "      \033[0;36mWhatsapp${exitsc} wa.me/6285881777396"
lane
exit
fi
}
checking_sc


function create(){
clear

garis
echo -e "${GREEN}| \E[44;1;39m      °NOOBZVPN'S CREATE°            \E[0m|"
garis
read -p "Username: " user
read -p "Password: " pass
read -p "Exp (0 for unlimited days):" exp
read -p "IP LIMIT " ip

if [ ! -e /etc/Tomketstore/limit/noobs/ip/ ]; then
  mkdir -p /etc/Tomketstore/limit/noobs/ip/
fi
echo "$ip" > /etc/Tomketstore/limit/noobs/ip/$user

noobzvpns --add-user $user $pass --expired-user $user $exp


clear

garis
echo -e "${CY}| \E[44;1;39m      °NOOBZVPN'S ACCOUNT°            \E[0m|"
garis
echo ""
echo -e "DOMAIN : $( cat /etc/xray/domain )"
echo -e "USERNAME: $user"
echo -e "PASSWORD: $pass"
echo -e "IP LIMIT: $ip"
echo -e "EXP DAYS: $exp DAYS"
echo -e "tcp_std port:  2082,8080"
echo -e "tcp_ssl port: 8443"
garis
echo -e "Example config TCP_STD 8080"
garis
echo ""
echo -e "EDIDC8xLjr94sgrR6IehsgLPpRclXF1EERoSyYTnnc6XBNoUiO15ycPgIjN6+4Fnl64TrMzt7+ipPucc1komuU/HCovp38yy6597g7cX16ZMAG4PrYaiVbZdElW3j97eyg0pUsDqYTHMAQSkLTJOW2RqK4t+tNjJSw1cBf3b11LgMFVhvqVjtcIKqEc1KSFu/ldcwikOIzijAffSH+dVWWLJVqZx5FpytM2QVSgLtY4a1BJRGopAVz86ACBtdWRsho6td7xgZHBx1Z5wjx4tC5XVQHdzqRY5TLBfkFtzOK2MHaTLWnEakvXk8TBJklppdIxFwJh1dyB/JBLjjcdQlBKbOQoV0v73YmNONau6vsesu2Ze7pHcytwK/UzLGoMIyfkrzLL3KEZ0bNMfES2ZY4EpqnziXG9XpQmpzsVZm3nxCYGoXbgRqDVWi7w5ugKVMGF9BYgOLKpYAg2OCoo+eSZfqTeTy0t2+Qck9QVtthdHOji65t5xTVkMu73/OYWVRhiQyYjnHS1DOTcdjton0RbW4uqAyP744Qrp95d7M/iGNSDV0r4aQ23efNMVcEgudIe5qvvcQ7tUBt6idapLWV/WEJyqF/sr01eagFJeKTnfn+RKp4+S1hjDeA=="
echo ""
garis
echo -e "Example config TCP_SSL 8443"
garis
echo ""

echo -e "ECOq4RB+/YwOpbWpR79ElbE/Zd5KQbkezRo8g8X5Bx+p44wV19V6xdipJySpDT3qdzsY4a19xMO9VsgOsPdRFR3icV2C9CzoX+RogckqL2awV2yYay0hhbGCDCveLK0+RTxR6cxT8CD99RUEdakNLbYje3PX4ZBQPuIui8DS3T4iWXcDzofuZLLRQKdvHXj69lZcsP/7njJT+Yd8ZG1v+alKRDeYSZJfUuvUJlxltKsGuzOgwdGHdesbKVdnmnfiBjn2SBXezVEpFBYSAgOTm4FlYtiIc5GyeDlFFac7h6zjNIai6XReJxbvvWTJ4ZC3zC1QLcSPuFzdHT+rFHrVLSqDtmBA4Kb8eqRYt7KCzZGX/rTE9LtdxUQwa/wH7E5GtyBSTmLbXdO76v0XVZWFmwsuGptWgKmfKrXrVjf0woVnKGRq4tn8y1ZdXAEf9WMQRpKyo6xZAtWQdCCIus3nbfM+GUtRTyjU6cl7C6rJaaWY8SDZoO8Dym7Tzwd84BEY7IJ2/xI0BJ/imci+DaQKHIOHzHt9SkBk6rQT3fFf0RbcKcsMNTdCrhbBknCi/H1PYF+15kjDA+FfAwpmS6BK26GKx98oDqgILzHIDa6k4i3Tqg=="
garis
echo -e "${GREEN}| \E[44;1;39m      ZERO STORE          \E[0m|"
garis

}


function delete(){
clear
garis
echo -e "${GREEN}| \E[44;1;39m      °NOOBZVPN'S DELETE°            \E[0m|"
garis
read -p "username :" user

noobzvpns --remove-user $user
clear
garis
echo -e "${GREEN}| \E[44;1;39m      °NOOBZVPN'S DELETED!°            \E[0m|"
garis
echo "USERNAME: $user"
echo "Delete success!!"
garis
echo -e "${GREEN}| \E[44;1;39m      ULTRAMEN STORE            \E[0m|"
garis
}


function renew(){
clear
garis
echo -e "${GREEN}| \E[44;1;39m      °NOOBZVPN'S RENEW°            \E[0m|"
garis
read -p "username: " user
read -p "expired?: " exp
noobzvpns --renew-user $user --expired-user $user $exp
clear
garis
echo -e "${GREEN}| \E[44;1;39m      °NOOBZVPN'S RENEW!°            \E[0m|"
garis
echo "USERNAME: $user"
echo "renew success!!"
garis
echo -e "${GREEN}| \E[44;1;39m      ULTRAMEN STORE            \E[0m|"
garis
}




function lock(){
clear
garis
echo -e "${GREEN}| \E[44;1;39m      °NOOBZVPN'S LOCK°            \E[0m|"
garis
read -p "username: " user
noobzvpns --block-user $user
clear
garis
echo -e "${GREEN}| \E[44;1;39m      °NOOBZVPN'S LOCK!°            \E[0m|"
garis
echo "USERNAME: $user"
echo "locked success!!"
garis
echo -e "${GREEN}| \E[44;1;39m      ULTRAMEN STORE            \E[0m|"
garis
}






function show(){

clear
garis
echo -e "${GREEN}| \E[44;1;39m      °NOOBZVPN'S MEMBER!°            \E[0m|"
garis
noobzvpns --info-all-user | awk '/^\s*\+.*-> active/ {gsub(/(issued\(yyyymmdd\)|hash_key): [0-9a-f]+/, ""); print; getline; print; getline; getline; getline; print; print "═══════════════════"}'

garis
echo -e "${GREEN}| \E[44;1;39m      ULTRAMEN STORE            \E[0m|"
garis
}



function unlock(){
clear
garis
echo -e "${GREEN}| \E[44;1;39m      °NOOBZVPN'S UNLOCK°            \E[0m|"
garis
read -p "username: " user
noobzvpns --unblock-user $user
clear
garis
echo -e "${GREEN}| \E[44;1;39m      °NOOBZVPN'S UNLOCK!°            \E[0m|"
garis
echo "USERNAME: $user"
echo "unlocked success!!"
garis
echo -e "${GREEN}| \E[44;1;39m      ULTRAMEN STORE            \E[0m|"
garis
}



function remove(){
clear
garis
echo -e "${GREEN}| \E[44;1;39m      °NOOBZVPN'S UNLOCK°            \E[0m|"
garis

read -p "Apakah Anda ingin menghapus semua user? (Y/N): " choice

if [ "$choice" == "Y" ] || [ "$choice" == "y" ]; then
    # Eksekusi perintah di sini
    echo "MENGHAPUS SEMUA USER!"
noobzvpns --remove-all-user
elif [ "$choice" == "N" ] || [ "$choice" == "n" ]; then
    echo "Membatalkan penghapusan."
menu-noobzvpns
else
    echo "Pilihan tidak valid."
fi

clear
garis
echo -e "${GREEN}| \E[44;1;39m      °NOOBZVPN'S UNLOCK!°            \E[0m|"
garis
echo "USERNAME: $user"
echo "unlocked success!!"
garis
echo -e "${GREEN}| \E[44;1;39m      ULTRAMEN STORE            \E[0m|"
garis
}




clear
garis
echo -e "${GREEN}| \E[44;1;39m      °NOOBZVPN'S SERVICE°            \E[0m|"
garis


echo -e "${LIGHT}"
echo -e "01.MENU CREATE ACCOUNT NOOBZVPNS"
echo -e "02.MENU DELETE ACCOUNT NOOBZVPNS"
echo -e "03.MENU RENEW ACCOUNT NOOBZVPNS"
echo -e "04.MENU LOCK ACCOUNT NOOBZVPNS"
echo -e "05.MENU UNLOCK ACCOUNT NOOBZVPNS"
echo -e "06.MENU SHOW ALL USER NOOBZVPNS"
echo -e "07.MENU REMOVE ALL USER NOOBZVPNS"
echo -e "00. BACK TO MAIN MENU"
garis
echo -e "${GREEN}| \E[44;1;39m            ULTRAMEN STORE            \E[0m|"
garis
echo -e ""
echo
read -p " Select menu : " opt
echo -e ""
case $opt in
01 | 1) clear ; create ;;
02 | 2) clear ; delete ;;
03 | 3) clear ; renew ;;
04 | 4) clear ; lock ;;
05 | 5) clear ; unlock ;;
06 | 6) clear ; show ;;
07 | 7) clear ; remove ;;
00 | 0) clear ; menu ;;
*) clear ; menu ;;
esac
